# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    # At 00:00 on Sunday
    - cron: "0 0 * * 0"
  pull_request:
    branches: [main, master]
name: build-readme
jobs:
  build-readme:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install packages
        run: Rscript -e 'install.packages(pkgs = c("dplyr", "tidyr", "stringr", "purrr", "knitr", "gh", "cranlogs"), repos = "http://cran.rstudio.com/"", type = "source")'
                        
      - name: Build Readme
        run: Rscript -e 'install.packages(pkgs = ".", repos = NULL, type = "source")'
                     -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      - name: Commit files
        run: |
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"
          git add --all
          git commit -am "chronjob"
          git push origin HEAD:refs/heads/master --force